### ISSUE TITLE
Enable page views on OFN-US

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/Analytics#12]
## What is the question we want to answer?
We'd like to have estimates on the number visitors for OFN-US website.

## What type of data do we need to answer this question (and how to get it, if known)?
Page view numbers can serve as a first approach to access this.

## Potential solutions that will solve the problem? [[brainstorming on how to access the data, using Matomo, Metabase, other]
We can set basic tracking using Matomo, by following [these steps](https://github.com/openfoodfoundation/openfoodnetwork/issues/9818#issuecomment-1284380370). 

## Additional context
The steps above are required since we've removed the general tracking code and installed the tag manager code. After doing so, we need to set up the correct trigger / tag / goal combination to re-enable page views / basic tracking.

We've discussed this [here](https://openfoodnetwork.slack.com/archives/C014V9TCWH5/p1699374474336579) recently and via huddle with @wuchristina

**Comment by wuchristina** [comment]
Thanks @filipefurtad0!  It appears that the OFN-US (& Aus) site is missing the Matomo snippets, which the FR one has - see screenshot.  It seems this needs to be updated in the Wordpress beforehand - how should we proceed?

![Screen Shot 2023-11-09 at 23 53 28](https://github.com/openfoodfoundation/Analytics/assets/91572452/512e2e93-bdfe-40df-888e-5eb344662fa5)

**Comment by filipefurtad0** [comment]
Hey @wuchristina ,

Oops, I should have been a bit more explicit about "OFN-US" site, I actually meant the e-commerce website / OFN-instance, which is at `https://openfoodnetwork.net/`, sorry my bad :see_no_evil:

The first step would be to create a container on Matomo - I just noticed there is none there:
![image](https://github.com/openfoodfoundation/Analytics/assets/49817236/997e1c21-31b2-4f7b-a76a-0b831c61dc88)

After that, you'll need to take the `Matomo Tag Manager URL` (which is in the Install code section - under that tiny `</>` button) and set it up on the OFN-US instance. We have a dedicated section on our user guide about this:
https://ofn-user-guide.gitbook.io/ofn-super-admin-guide/ofn-platform-configuration/matomo

Once you have the required values to fill in that page, you'll need to ping a user with superadmin rights to do that for you, on the US instance - @lauriewayne might be able to help there :-)

In the end, it should look more or less like this - as an example I'm sharing the settings from one of our staging servers:
![image](https://github.com/openfoodfoundation/Analytics/assets/49817236/1e314925-1c89-4527-ae61-f3422abf550d)

It is actually only after this is concluded, that we can move on to [create triggers/tags](https://github.com/openfoodfoundation/openfoodnetwork/issues/9818#issuecomment-1284380370) and have them take effect on tracking.

In any case, and about the Wordpress website - you're totally correct: the tracking code is set directly on that website, but I'm not entirely sure how to proceed on that, as it is currently not using Tag Manager tracking code, but the old general tracking code.

**Comment by wuchristina** [comment]
Thanks @filipefurtad0 for the clarifications, I've created the container & slacked @lauriewayne.  Will update with progress.

**Comment by lauriewayne** [comment]
I am always so grateful for the clarity of our guides and for people like @filipefurtad0. @wuchristina I think we're set at openfoodnetwork.net. Happy to change or adjust as required!

**Comment by wuchristina** [comment]
Thanks @lauriewayne for the update on openfoodnetwork.net - the visits are counting!  

@filipefurtad0 it looks like about.openfoodnetwork.net needs the container code as well, as I think it would be useful to see visits by page.  Laurie says that the About is on Wordpress & that someone in the community would know how to do that.  I haven't seen anything else looking through GitHub so far (do let me know if I missed!) so wondering if you could direct me to who could help with adding the container code on Wordpress?

**Comment by lauriewayne** [comment]
Oh gosh, looks like that is also well documented in the super admin guide! Sorry @wuchristina ! 
☺️ I'll install the plug-in and take a swing at setting it up this evening.

**Comment by filipefurtad0** [comment]
> Thanks @lauriewayne for the update on openfoodnetwork.net - the visits are counting!

:star_struck: 

![image](https://github.com/openfoodfoundation/Analytics/assets/49817236/fc973197-8e4a-4873-b521-69599b2639b5)

Nice work @wuchristina @lauriewayne :clap: :clap: :clap:

**Comment by wuchristina** [comment]
Update: the container code was added successfully to about.openfoodnetwork.net by @lauriewayne on Friday 🙌

I have also added "Visits About Us" & "Visits Shop Now" goals, for now.  Still looking through documentation & will ping @filipefurtad0 to connect on setting up funnels / next steps.

**Comment by filipefurtad0** [comment]
Sure, @wuchristina ,
Happy to chat on how to set other goals/funnels.

Since you've addressed the page views on OFN-US (yayy :muscle:)  I think we can close this issue now. And then maybe open a new ones, if needed, for the analytics questions you're aiming to answer. Does this sound good? If so, feel free to hit the close button below ;-)

Happy to chat anytime, when you need any help :slightly_smiling_face:

**Comment by wuchristina** [comment]
Great!  Thanks @filipefurtad0, will do & marking this issue as resolved then 🤝
